### PR TITLE
Drone Series - Collision Avoidance Part 1 submission with fixing lint errors

### PR DESCRIPTION
**Pull request by billsedison**
Hi, this is the PR of the winning submission of billsedison. I have fixed lint errors as the review required. Please check, thanks.

### CODE REVIEW

**Comment by gondzo** [comment]
@billsedison the target branch is "dev", not master. can you fix the postman merge issues ?

**Comment by billsedison** [comment]
OK, I will create a PR soon.
On 01/08/2017 17:58, gondzo wrote:

@billsedison the target branch is "dev", not master. can you fix the postman merge issues ?

**Comment by gondzo** [comment]
also, please update service response to return "id" instead of "_id"

**Comment by billsedison** [comment]
OK. And sorry I'm offline in recent hours. I will try to create a new PR ASAP
On 01/08/2017 20:21, gondzo wrote:

also, please update service response to return "id" instead of "_id"

**Comment by billsedison** [comment]
I created a new PR #165 to resolve the issues stated above. This PR is closed.

**Pull request closed without merging**
